use_frameworks!

target 'JESwiftKit_Example' do
  pod 'JESwiftKit', :path => '../'

  target 'JESwiftKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
