use_frameworks!

target 'JESwiftKit_Example' do
  pod 'JESwiftKit', :path => '../'
  pod 'JESwiftKit/Rx', :path => '../'
  pod 'JESwiftKit/Lottie', :path => '../'

  target 'JESwiftKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3'
    pod 'Nimble', '~> 7.0'
  end
end
